/**
 * Static knowledge corpus – generated from website content.
 *
 * Regenerated by `scripts/build-knowledge.ts` on every build/deploy.
 * BUILD_ID is replaced at build time with the git SHA or deploy ID.
 *
 * Content is extracted from:
 *  - Public marketing pages
 *  - Legal pages (terms, privacy)
 *  - Dashboard help content
 *  - Backend policy constants
 *  - FAQ content
 */

import type { KnowledgeDocument } from "./types"
import {
  DEPOSIT_AMOUNT,
  COMMISSION_RATES,
  AUCTION_DURATION_HOURS,
  PREQUAL_EXPIRY_DAYS,
  MAX_SHORTLIST_ITEMS,
  CREDIT_TIERS,
  CONTRACT_SHIELD_THRESHOLDS,
  PREMIUM_FEE,
} from "@/lib/constants"

// Build metadata — read from environment at module load time.
// NEXT_PUBLIC_BUILD_ID or VERCEL_GIT_COMMIT_SHA are set during deploy/build.
const BUILD_ID = process.env.NEXT_PUBLIC_BUILD_ID ?? process.env.VERCEL_GIT_COMMIT_SHA ?? "dev"
const UPDATED_AT = new Date().toISOString()

export const knowledgeCorpus: KnowledgeDocument[] = [
  // ─── PUBLIC MARKETING ──────────────────────────────────────────────
  {
    id: "homepage-intro",
    title: "AutoLenis — What Is It?",
    text: `AutoLenis is an AI-powered car buying concierge platform. It is NOT a dealership, lender, or law firm. AutoLenis structures the negotiation process online so dealers compete and buyers stay in control. The platform offers a 100% online process with AI-driven dealer competition, transparent pricing, and a buyer-aligned model. AutoLenis may charge dealers platform access fees (subscription or participation-based). AutoLenis facilitates a secure, transparent workflow — it does not guarantee outcomes.`,
    url: "/",
    visibility: "public",
    tags: ["overview", "what-is-autolenis"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "pricing-fees",
    title: "AutoLenis Pricing — Free & Premium Plans",
    text: `AutoLenis offers two plans: Free Plan (no cost to start) and Premium ($${PREMIUM_FEE} concierge fee). A $${DEPOSIT_AMOUNT} Serious Buyer Deposit is required to start the auction for both plans. On the Free plan, the deposit is credited toward the vehicle purchase at closing (purchase credit / due-at-signing credit). On the Premium plan, the deposit is credited toward the $${PREMIUM_FEE} concierge fee ($${PREMIUM_FEE - DEPOSIT_AMOUNT} remaining). If no dealer offers are received, the $${DEPOSIT_AMOUNT} deposit is refundable. AutoLenis may charge dealers platform access fees. No hidden fees beyond standard dealer/DMV/tax costs.`,
    url: "/pricing",
    visibility: "public",
    tags: ["fees", "pricing", "deposit", "cost"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "pricing-free-plan",
    title: "Free Plan — What's Included",
    text: `The Free plan (no cost to start) includes: instant pre-qualification, silent reverse auction among dealers, best price engine, Contract Shield AI verification, insurance quotes, e-signature and QR pickup, and standard support. The $${DEPOSIT_AMOUNT} Serious Buyer Deposit is credited toward your vehicle purchase at closing.`,
    url: "/pricing",
    visibility: "public",
    tags: ["fees", "pricing", "free-plan"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "pricing-premium-plan",
    title: `Premium Plan ($${PREMIUM_FEE}) — Full-Service Concierge`,
    text: `The Premium plan ($${PREMIUM_FEE} concierge fee) is our complete end-to-end white-glove buying service. It includes everything in the Free plan plus: full-service buying support from start to finish, dedicated buying specialist, priority dealer handling, financing assistance to help find the right loan options, a smarter financing process designed to reduce unnecessary inquiries, contract review and closing coordination, free home delivery, and priority support. The $${DEPOSIT_AMOUNT} Serious Buyer Deposit is credited toward the $${PREMIUM_FEE} fee ($${PREMIUM_FEE - DEPOSIT_AMOUNT} remaining). Free home delivery is included for Premium buyers, subject to delivery area eligibility and scheduling availability.`,
    url: "/pricing",
    visibility: "public",
    tags: ["fees", "pricing", "premium-plan"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "pricing-payment-options",
    title: "How to Pay the Concierge Fee",
    text: `Two payment options for the Premium concierge fee: (1) Pay Directly (recommended) — credit/debit card, doesn't affect the loan. (2) Include in Loan — added to financing with a transparent impact calculation showing the difference in monthly payment. Note: the $${DEPOSIT_AMOUNT} Serious Buyer Deposit is always credited toward the fee on the Premium plan.`,
    url: "/pricing",
    visibility: "public",
    tags: ["fees", "pricing", "payment"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── HOW IT WORKS ──────────────────────────────────────────────────
  {
    id: "how-it-works-overview",
    title: "How AutoLenis Works — 5-Step Process",
    text: `Step 1: Application & Consent — Secure form with clear privacy disclosures and explicit data consent. Step 2: Secure Lender Connection — Application routed to participating lenders/credit unions; lenders make credit decisions. Step 3: Dealer Matching — Connection with licensed dealers matching your criteria. Step 4: Review & Compare — Transparent offer comparison with clear pricing breakdown and no-pressure approach. Step 5: Complete Purchase — Finalize directly with dealer; sign digitally or in-person; schedule pickup/delivery.`,
    url: "/how-it-works",
    visibility: "public",
    tags: ["process", "steps", "how-it-works"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Core Value & Differentiation ─────────────────────────────
  {
    id: "faq-what-is-autolenis",
    title: "FAQ: What exactly is AutoLenis?",
    text: `AutoLenis is an end-to-end car-buying concierge platform that helps buyers go from pre-qualification to pickup through a structured workflow — so they can shop smarter, avoid pressure, and reduce surprises. AutoLenis is NOT a dealership, lender, or law firm.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "overview", "what-is-autolenis"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-vs-dealer",
    title: "FAQ: AutoLenis vs Going Directly to a Dealer",
    text: `Direct-to-dealer usually means you negotiate alone inside the dealer's environment. AutoLenis shifts leverage by structuring the process so dealers compete for your deal and the paperwork is checked before you commit. Dealers still sell the car; AutoLenis improves the workflow.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "differentiation", "dealers", "comparison"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-vs-free-broker",
    title: 'FAQ: AutoLenis vs "Free" Brokers',
    text: `"Free" often means the broker's incentive is aligned to the dealer payout — not necessarily the buyer's best deal. AutoLenis is built to create process leverage and verification, not just referrals. The real cost of a free broker is often: higher total price, financing padding, limited transparency, pressure to close, and reduced recourse when the deal changes.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "differentiation", "broker", "comparison"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-problems-solved",
    title: "FAQ: What problems does AutoLenis solve?",
    text: `AutoLenis addresses time waste, negotiation pressure, confusing fees, contract surprises, insurance delays, and "deal drift" where the final numbers change at signing. Buyers want control, clarity, and fewer surprises — without spending weeks negotiating and second-guessing paperwork.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "overview", "value"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-credit-agnostic",
    title: "FAQ: Is AutoLenis only for people with bad credit?",
    text: `No. AutoLenis is for buyers who want a clean, controlled process — whether their credit is strong or still improving. AutoLenis is designed to increase leverage by creating structured competition and reducing friction, but no platform can guarantee a specific price outcome.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "credit", "eligibility"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Fees, Value & ROI ──────────────────────────────────────
  {
    id: "faq-fees",
    title: "FAQ: What do the fees actually pay for?",
    text: `AutoLenis offers a Free Plan (no cost) and a Premium plan ($${PREMIUM_FEE} concierge fee). Fees pay for a structured system: qualification flow, sourcing/offer workflow, coordination, contract verification (Contract Shield), guided next steps, and concierge support. A $${DEPOSIT_AMOUNT} Serious Buyer Deposit is required to start the auction. On the Free plan the deposit is credited toward your vehicle purchase at closing. On the Premium plan it is credited toward the $${PREMIUM_FEE} fee ($${PREMIUM_FEE - DEPOSIT_AMOUNT} remaining). The deposit is refundable if no offers are received.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "fees", "pricing", "deposit"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-fee-vs-markup",
    title: "FAQ: How is the fee different from a markup?",
    text: `A markup is hidden in the deal; the AutoLenis fee is explicit. Buyers pay for process execution and protection instead of guessing where the cost got buried. Even strong negotiators benefit because AutoLenis is as much about verification and workflow control as negotiation.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "fees", "pricing", "value"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-fee-justification",
    title: "FAQ: Why is the fee worth it?",
    text: `The fee pays for leverage and protection — two things that are hard to get "free" in a dealer-driven transaction. The real cost is often hidden in price, financing terms, add-ons, time, and mistakes. AutoLenis standardizes steps, reduces repeated negotiations, and keeps everything in one guided workflow. Value isn't just price — it's reducing avoidable risk and time loss.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "fees", "value", "roi"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-pay-if-no-buy",
    title: "FAQ: Do I pay if I don't buy?",
    text: `AutoLenis can be structured with different fee triggers; the clean rule is: you pay for work performed and/or when you choose to proceed (exact policy depends on the current fee model). If no dealer offers are received, the $${DEPOSIT_AMOUNT} deposit is automatically refunded.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "fees", "refund", "deposit"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Trust & Independence ───────────────────────────────────
  {
    id: "faq-trust-independence",
    title: "FAQ: Trust, independence, and incentive alignment",
    text: `AutoLenis discloses compensation sources clearly. If any dealer-side compensation exists, it must be transparent and never compromise buyer confidentiality. The platform routes offers through a structured process; any dealer ranking is based on objective factors (responsiveness, verified terms, compliance, customer outcomes). Buyers keep decision control. Data minimization and permission-based sharing are the default. Dealers cannot see competitor pricing or identities — this preserves real competition.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "trust", "independence", "incentives", "privacy"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Process / Buyer Journey ─────────────────────────────────
  {
    id: "faq-timeline",
    title: "FAQ: What are the steps and how long does it take?",
    text: `The buyer journey: prequal → vehicle request/shortlist → offers/competition → select best offer → fees/financing → insurance → contract verification → e-sign → pickup/delivery. Timing depends on inventory and responsiveness, but AutoLenis is designed to compress delays by standardizing every step and keeping momentum. Buyers typically have far less direct dealer communication than normal — keeping it structured and limited until they're ready.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "timeline", "process", "steps"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-negative-equity",
    title: "FAQ: What if I'm upside down on my current car?",
    text: `AutoLenis can structure the deal path to account for payoff/negative equity considerations — without pretending it disappears. AutoLenis can also guide your vehicle request into a tight spec (budget, mileage, features, must-haves) so offers are relevant.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "process", "trade-in", "negative-equity"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Offers & Competition ────────────────────────────────────
  {
    id: "faq-auction",
    title: "FAQ: How do offers and the silent reverse auction work?",
    text: `In AutoLenis's silent reverse auction, dealers cannot see competing bids. This creates genuine competition and prevents collusion. The auction runs for ${AUCTION_DURATION_HOURS} hours. You submit a defined request; dealers respond with structured offers; you compare and select — without typical showroom pressure. Counter-offers can be supported through structured terms. The full cost breakdown (vehicle price, fees, taxes, add-ons, financing terms) should be clearly presented. If no dealer offers are received, the $${DEPOSIT_AMOUNT} deposit is automatically refunded. You are never obligated to accept any offer.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "auction", "dealers", "offers", "competition"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-bait-switch",
    title: "FAQ: What stops a dealer from bait-and-switch?",
    text: `Process controls, documentation checks, and the ability to pause or stop when numbers change. AutoLenis pushes deal confirmation and documentation checks earlier — so discrepancies surface before you're at the desk, not at signing. You can proceed with outside financing; AutoLenis still adds value on process, contract verification, and coordination.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "offers", "protection", "bait-switch"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Contract Shield & Verification ──────────────────────────
  {
    id: "faq-contract-shield",
    title: "FAQ: What is Contract Shield?",
    text: `Contract Shield is a contract verification layer designed to catch inconsistencies, missing disclosures, and unexpected add-ons before you commit. It can catch: unexpected products/add-ons, fee mismatches, term inconsistencies, missing required disclosures, or payment numbers that don't match the offer. Contract Shield is NOT legal advice — it is a verification and clarity tool, not a substitute for an attorney. If the contract is flagged, the transaction pauses, the issues are identified, and the dealer can correct them — or AutoLenis routes the situation through a controlled review path. Many bad deals happen at signing — when fatigue, pressure, and complexity are highest. Pass threshold: ${CONTRACT_SHIELD_THRESHOLDS.PASS}%, Warning: ${CONTRACT_SHIELD_THRESHOLDS.WARNING}%, Fail: below ${CONTRACT_SHIELD_THRESHOLDS.FAIL}%.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "contract-shield", "contract", "verification"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Insurance & Completion ──────────────────────────────────
  {
    id: "faq-insurance-completion",
    title: "FAQ: Insurance, pickup/delivery, and completing the deal",
    text: `AutoLenis can support insurance quote workflows or verification so you don't get stuck at delivery. You are not required to buy insurance through AutoLenis — you can use your own provider; AutoLenis helps ensure you meet the dealer's proof requirements on time. Once contract and insurance steps are satisfied, the platform coordinates pickup/delivery scheduling and confirms requirements. AutoLenis should generate a clear checklist so you don't lose the car or delay closing.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "insurance", "pickup", "delivery", "completion"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── FAQ — Edge Cases & Support ────────────────────────────────────
  {
    id: "faq-edge-cases-support",
    title: "FAQ: Edge cases, support, and control",
    text: `If there are no dealers in your area yet, AutoLenis can route you into a sourcing path — collecting top vehicle preferences and expanding outreach until offers can be obtained. You can revise your request at any time; the process is structured, not punitive. If you find a car on your own, AutoLenis can still add value by verifying terms, supporting the contract stage, and guiding you through completion steps. If something goes wrong mid-transaction, AutoLenis gives you a controlled escalation path — documented, trackable, and easier to resolve than ad-hoc texting and calls. Lenis Concierge can answer immediately about process and status, and escalate to human support when required.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "support", "concierge", "edge-cases"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-why-autolenis",
    title: "FAQ: Why AutoLenis instead of the old way?",
    text: `AutoLenis turns a chaotic, dealer-led negotiation into a structured, verified, buyer-controlled workflow — so buyers reduce surprises, save time, and complete with confidence. The five pillars: (1) Leverage — dealers compete for your deal; you keep control. (2) Protection — contract review and process guardrails reduce "surprise costs." (3) Speed + Simplicity — one workflow from prequal to offer to contract to insurance to pickup. (4) Transparency — clear steps, clear status, clear responsibilities. (5) Real economics — "free" often means you pay indirectly through markup, rate padding, wasted time, or pressure.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "overview", "value", "differentiation", "summary"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-prequal",
    title: "FAQ: How does pre-qualification work?",
    text: `Pre-qualification uses a soft credit pull that does NOT impact your credit score. A hard inquiry occurs only at the point of final financing. Pre-qualification provides conditional estimates, not a guarantee of approval. Final approval depends on lender underwriting. Pre-qualification results are valid for ${PREQUAL_EXPIRY_DAYS} days.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "prequal", "credit", "soft-pull"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-financing",
    title: "FAQ: Can I use my own financing?",
    text: `Yes. You can use your own financing (bank or credit union pre-approval) or use AutoLenis's lending partners. The concierge fee can be included in the loan, with a transparent impact calculation showing the monthly payment difference. AutoLenis still adds value on process, contract verification, and coordination.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "financing", "loan"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-pickup",
    title: "FAQ: How does pickup work?",
    text: `Pickup is at the dealership using a unique QR code. Once contract and insurance steps are satisfied, the platform coordinates pickup/delivery scheduling and confirms requirements. AutoLenis generates a clear checklist so you know exactly what to bring.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "pickup", "delivery"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "faq-shortlist",
    title: "FAQ: How many vehicles can I shortlist?",
    text: `You can shortlist up to ${MAX_SHORTLIST_ITEMS} vehicles at a time.`,
    url: "/faq",
    visibility: "public",
    tags: ["faq", "shortlist", "vehicles"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── CREDIT & ELIGIBILITY POLICIES ─────────────────────────────────
  {
    id: "policy-credit-tiers",
    title: "Credit Score Tiers & Eligibility",
    text: `AutoLenis uses four credit tiers: Excellent (${CREDIT_TIERS.EXCELLENT.min}-${CREDIT_TIERS.EXCELLENT.max}), Good (${CREDIT_TIERS.GOOD.min}-${CREDIT_TIERS.GOOD.max}), Fair (${CREDIT_TIERS.FAIR.min}-${CREDIT_TIERS.FAIR.max}), Poor (${CREDIT_TIERS.POOR.min}-${CREDIT_TIERS.POOR.max}). These tiers affect estimated APR rates offered by lenders but do not guarantee any specific rate. Final rates are determined by the lender after underwriting.`,
    url: "/faq",
    visibility: "public",
    tags: ["credit", "eligibility", "tiers"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "policy-soft-hard-pull",
    title: "Soft vs Hard Credit Pull Policy",
    text: `Pre-qualification at AutoLenis uses a soft credit inquiry that does NOT affect your credit score. This lets you see estimated terms without commitment. A hard credit inquiry occurs only when you choose to proceed with final financing through a lender. Hard inquiries may have a small, temporary impact on your credit score. AutoLenis is transparent about when each type occurs.`,
    url: "/faq",
    visibility: "public",
    tags: ["credit", "soft-pull", "hard-pull", "prequal"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── INSURANCE ─────────────────────────────────────────────────────
  {
    id: "insurance-overview",
    title: "Insurance Requirements & Options",
    text: `Insurance is required before completing a vehicle purchase. Two paths: (1) Compare Quotes — get quotes from 5+ providers instantly; see coverage details; purchase through AutoLenis; automatic verification. (2) Upload Existing — upload your insurance card/declaration page; instant approval in most cases. Insurance is required because: most states require proof before driving off the lot, it provides financial coverage from accidents/theft/damage, and lenders require comprehensive/collision coverage for financed vehicles.`,
    url: "/insurance",
    visibility: "public",
    tags: ["insurance", "coverage", "requirements"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── CONTACT ───────────────────────────────────────────────────────
  {
    id: "contact-info",
    title: "AutoLenis Contact Information",
    text: `Email: info@autolenis.com. Phone: (469) 214-2132. Address: 12800 Westridge Blvd, Ste 114, Frisco, TX 75035. Hours: Mon-Fri 9am-6pm CST, Sat 10am-4pm CST, Sunday closed. Privacy inquiries: privacy@autolenis.com.`,
    url: "/contact",
    visibility: "public",
    tags: ["contact", "support", "hours"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── LEGAL — TERMS OF SERVICE ──────────────────────────────────────
  {
    id: "terms-overview",
    title: "Terms of Service — Key Points",
    text: `AutoLenis is NOT a lender, dealer, or financial institution — it is a concierge platform only. The $${DEPOSIT_AMOUNT} deposit is refundable if no dealer offers are received and is credited toward the concierge fee on completion. Services include: pre-qualification, vehicle search, reverse auction, Contract Shield, insurance coordination, e-signature, and pickup scheduling. Contract Shield is an information tool only — it does not provide legal/tax/financial advice and does not guarantee contract correctness. AutoLenis does not guarantee loan approval, rates, vehicle availability, or specific pricing. Users must review all documents before signing. AutoLenis is not responsible for third-party lender/dealer actions. Governing law: Delaware. Disputes: binding arbitration (AAA).`,
    url: "/legal/terms",
    visibility: "public",
    tags: ["terms", "legal", "policy"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "terms-refund-cancellation",
    title: "Refund & Cancellation Policy",
    text: `The $${DEPOSIT_AMOUNT} deposit is refundable if no dealer offers are received during the auction. Once an offer is accepted and the auction has concluded, the concierge fee is non-refundable. The deposit is credited toward the total concierge fee. Users can cancel at any time before accepting an offer with no penalty beyond forfeiting any non-refundable portions.`,
    url: "/legal/terms",
    visibility: "public",
    tags: ["refund", "cancellation", "deposit", "policy"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── LEGAL — PRIVACY ──────────────────────────────────────────────
  {
    id: "privacy-data-collected",
    title: "Privacy Policy — Data We Collect",
    text: `Data collected with consent: Personal info (name, email, phone, SSN, employment, income, DOB, driver's license, payment info), credit reports/scores from bureaus, usage data (IP, browser type, pages visited), and vehicle preferences/search history/shortlist data. AutoLenis never sells personal information.`,
    url: "/legal/privacy",
    visibility: "public",
    tags: ["privacy", "data", "legal"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "privacy-data-sharing",
    title: "Privacy Policy — Who We Share Data With",
    text: `Data is shared with: Lenders (for financing applications), Dealers (vehicle preferences and pre-qualified budget only — NOT full credit report), Service Providers (credit bureaus, payment processors, insurance, e-signature — with data protection agreements), Affiliates (limited info for commission calculation), and Legal (if required by law/court order). Data is encrypted in transit and at rest.`,
    url: "/legal/privacy",
    visibility: "public",
    tags: ["privacy", "data-sharing", "legal"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "privacy-user-rights",
    title: "Privacy Policy — Your Data Rights",
    text: `Users can contact privacy@autolenis.com to: access personal data, correct inaccurate info, delete data (subject to legal retention requirements), opt-out of marketing, and restrict data processing. California residents have additional CCPA rights including the right to know what personal info is collected and the right to opt-out of sale/sharing of personal information.`,
    url: "/legal/privacy",
    visibility: "public",
    tags: ["privacy", "rights", "ccpa", "legal"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── AFFILIATE ─────────────────────────────────────────────────────
  {
    id: "affiliate-commissions",
    title: "Affiliate Commission Structure",
    text: `Affiliate commissions are paid only on completed deals where the concierge fee has been received. Commission rates: Level 1 (direct referral): ${COMMISSION_RATES.LEVEL_1 * 100}%, Level 2: ${COMMISSION_RATES.LEVEL_2 * 100}%, Level 3: ${COMMISSION_RATES.LEVEL_3 * 100}%. Commissions are taxable income for the affiliate.`,
    url: "/affiliate",
    visibility: "public",
    tags: ["affiliate", "commissions", "payouts"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── BUYER DASHBOARD HELP ──────────────────────────────────────────
  {
    id: "buyer-dashboard-overview",
    title: "Buyer Dashboard — Getting Started",
    text: `Your buyer dashboard shows your current deal status, active auctions, offers received, documents needed, and next steps. You can: start or refresh your pre-qualification, create a vehicle request, track your auction, review and compare offers, upload required documents, and view your contract details. Each step in the process has a clear status indicator.`,
    url: "/buyer",
    visibility: "buyer",
    tags: ["buyer", "dashboard", "help"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
  {
    id: "buyer-documents-required",
    title: "Buyer — Required Documents",
    text: `Documents that may be required during the purchase process: valid driver's license, proof of income (pay stubs, tax returns), proof of residence (utility bill, bank statement), proof of insurance, trade-in title (if applicable). Documents are uploaded securely through the platform — never share sensitive documents in chat.`,
    url: "/buyer",
    visibility: "buyer",
    tags: ["buyer", "documents", "upload"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── DEALER DASHBOARD HELP ─────────────────────────────────────────
  {
    id: "dealer-dashboard-overview",
    title: "Dealer Dashboard — Overview",
    text: `The dealer dashboard shows active buyer requests, your submitted offers, accepted deals, required document uploads, and pickup scheduling. Dealers participate in silent reverse auctions where they cannot see competing bids. Offers must include all fees and the out-the-door price. Timely document submission and response to Contract Shield flags is required.`,
    url: "/dealer",
    visibility: "dealer",
    tags: ["dealer", "dashboard", "help"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── AFFILIATE DASHBOARD HELP ──────────────────────────────────────
  {
    id: "affiliate-dashboard-overview",
    title: "Affiliate Dashboard — Overview",
    text: `Your affiliate dashboard shows your referral link, total referrals, active deals from referrals, commission earnings, pending payouts, and attribution details. Commissions are earned only on completed deals where the concierge fee has been collected. Use your unique referral link to track attribution.`,
    url: "/affiliate",
    visibility: "affiliate",
    tags: ["affiliate", "dashboard", "help"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── ADMIN HELP ────────────────────────────────────────────────────
  {
    id: "admin-dashboard-overview",
    title: "Admin Dashboard — Overview",
    text: `The admin dashboard provides access to: user management (search, view, modify roles), dealer management (onboarding, compliance, status), affiliate management (commissions, payouts, reconciliation), deal oversight (active deals, auctions, contracts), payment tracking, and system reports. Sensitive actions (role changes, refunds, payout reconciliation) require confirmation. All admin actions are logged for audit.`,
    url: "/admin",
    visibility: "admin",
    tags: ["admin", "dashboard", "help"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── REFINANCE ─────────────────────────────────────────────────────
  {
    id: "refinance-overview",
    title: "AutoLenis Refinance Options",
    text: `AutoLenis offers vehicle refinancing to help lower monthly payments or get a better interest rate. The refinance process considers your current loan details, vehicle condition (Excellent, Good, Fair, Poor), and credit profile. Refinancing is subject to lender approval and does not guarantee specific rates or savings. AutoLenis connects you with lenders — it does not issue loans directly.`,
    url: "/refinance",
    visibility: "public",
    tags: ["refinance", "loan", "rates"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },

  // ─── AFFORDABILITY CALCULATOR ──────────────────────────────────────
  {
    id: "calculator-affordability",
    title: "Affordability Calculator — How It Works",
    text: `The affordability calculator estimates what you might afford based on: monthly income, housing costs, down payment, and credit score. It uses a 12% payment-to-income (PTI) cap, a $275/month insurance/maintenance buffer, 10% estimated tax/fees, and a default 60-month loan term. Results are estimates only — not a credit decision or loan offer. Final terms depend on lender approval. Use the official calculator tool for accurate estimates.`,
    url: "/pricing",
    visibility: "public",
    tags: ["calculator", "affordability", "payment", "estimate"],
    updatedAt: UPDATED_AT,
    buildId: BUILD_ID,
  },
]
