// Canonical DealStatus values matching the Prisma schema enum.
// Defined here to avoid pnpm module-resolution issues with @prisma/client enum re-exports.
export const DealStatus = {
  SELECTED: "SELECTED",
  FINANCING_PENDING: "FINANCING_PENDING",
  FINANCING_APPROVED: "FINANCING_APPROVED",
  FEE_PENDING: "FEE_PENDING",
  FEE_PAID: "FEE_PAID",
  INSURANCE_PENDING: "INSURANCE_PENDING",
  INSURANCE_COMPLETE: "INSURANCE_COMPLETE",
  CONTRACT_PENDING: "CONTRACT_PENDING",
  CONTRACT_REVIEW: "CONTRACT_REVIEW",
  CONTRACT_MANUAL_REVIEW_REQUIRED: "CONTRACT_MANUAL_REVIEW_REQUIRED",
  CONTRACT_INTERNAL_FIX_IN_PROGRESS: "CONTRACT_INTERNAL_FIX_IN_PROGRESS",
  CONTRACT_ADMIN_OVERRIDE_APPROVED: "CONTRACT_ADMIN_OVERRIDE_APPROVED",
  CONTRACT_APPROVED: "CONTRACT_APPROVED",
  SIGNING_PENDING: "SIGNING_PENDING",
  SIGNED: "SIGNED",
  PICKUP_SCHEDULED: "PICKUP_SCHEDULED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
} as const

export type DealStatus = (typeof DealStatus)[keyof typeof DealStatus]

export type PaymentType = "CASH" | "FINANCED" | "EXTERNAL_PREAPPROVAL"
export type ConciergeFeeMethod = "CARD_DIRECT" | "LENDER_DIRECT" | "UNDECIDED"
export type ConciergeFeeStatus = "NOT_APPLICABLE" | "PENDING" | "PAID" | "INCLUDED_IN_LOAN" | "REFUNDED"

// Normalize legacy status values to Prisma DealStatus
const LEGACY_STATUS_MAP: Record<string, DealStatus> = {
  PENDING_FINANCING: "FINANCING_PENDING",
  FINANCING_CHOSEN: "FINANCING_APPROVED",
  INSURANCE_READY: "INSURANCE_PENDING",
  CONTRACT_PASSED: "CONTRACT_APPROVED",
}

export function normalizeDealStatus(s: unknown): DealStatus | null {
  if (typeof s !== "string") return null
  // Already a valid Prisma value
  if (Object.values(DealStatus).includes(s as DealStatus)) return s as DealStatus
  // Map known legacy values
  return LEGACY_STATUS_MAP[s] ?? null
}

// Valid status transitions (Prisma DealStatus values only)
export const VALID_TRANSITIONS: Partial<Record<DealStatus, DealStatus[]>> = {
  SELECTED: ["FINANCING_PENDING", "CANCELLED"],
  FINANCING_PENDING: ["FINANCING_APPROVED", "CANCELLED"],
  FINANCING_APPROVED: ["FEE_PENDING", "FEE_PAID", "INSURANCE_PENDING", "INSURANCE_COMPLETE", "CONTRACT_PENDING", "CANCELLED"],
  FEE_PENDING: ["FEE_PAID", "CANCELLED"],
  FEE_PAID: ["INSURANCE_PENDING", "INSURANCE_COMPLETE", "CONTRACT_PENDING", "CANCELLED"],
  INSURANCE_PENDING: ["INSURANCE_COMPLETE", "CONTRACT_PENDING", "CANCELLED"],
  INSURANCE_COMPLETE: ["CONTRACT_PENDING", "CANCELLED"],
  CONTRACT_PENDING: ["CONTRACT_REVIEW", "CONTRACT_APPROVED", "CANCELLED"],
  CONTRACT_REVIEW: ["CONTRACT_APPROVED", "CONTRACT_MANUAL_REVIEW_REQUIRED", "CANCELLED"],
  CONTRACT_MANUAL_REVIEW_REQUIRED: ["CONTRACT_APPROVED", "CONTRACT_ADMIN_OVERRIDE_APPROVED", "CONTRACT_INTERNAL_FIX_IN_PROGRESS", "CONTRACT_REVIEW", "CANCELLED"],
  CONTRACT_INTERNAL_FIX_IN_PROGRESS: ["CONTRACT_MANUAL_REVIEW_REQUIRED", "CONTRACT_REVIEW", "CANCELLED"],
  CONTRACT_ADMIN_OVERRIDE_APPROVED: ["CONTRACT_APPROVED", "CONTRACT_MANUAL_REVIEW_REQUIRED", "SIGNING_PENDING", "SIGNED", "CANCELLED"],
  CONTRACT_APPROVED: ["SIGNING_PENDING", "SIGNED", "CANCELLED"],
  SIGNING_PENDING: ["SIGNED", "CANCELLED"],
  SIGNED: ["PICKUP_SCHEDULED", "CANCELLED"],
  PICKUP_SCHEDULED: ["COMPLETED", "CANCELLED"],
  COMPLETED: [],
  CANCELLED: [],
}
